# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d09ee8cecd1ac49cc7eee91740f1fd0a58b17975595eb2f74384d2d01d0df1b7ed071b34e649705a44c717effdf099674ea6784f08742afb395ab1dfc4948f78

test:
  secret_key_base: a5f97e1fb52e134b3998c4ca1abfb64920549bdbdce7821e334254a4107c898d60d43d08361d8851b6e65acdd74eff45c61c7a600aa2bb468efa4221955c60b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
